name: Test Docker build

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  # Step 1: Build the Docker image once
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t meeran_assignment ./task_assignment
      - name: Save Docker image as artifact
        run: docker save meeran_assignment:latest | gzip > meeran_assignment.tar.gz
      - uses: actions/upload-artifact@v4
        with:
          name: meeran_assignment
          path: meeran_assignment.tar.gz

  # # Step 2: Run Robot State test
  # test_robot_state:
  #   needs: build-docker
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/download-artifact@v4
  #       with:
  #         name: meeran_assignment
  #     - name: Load Docker image
  #       run: docker load < meeran_assignment.tar.gz
  #     - name: Run Robot State test
  #       run: |
  #         docker run --rm \
  #           -v "${{ github.workspace }}/task_assignment:/assignment" \
  #           -w /assignment \
  #           meeran_assignment \
  #           bash -c '
  #             cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug &&
  #             cmake --build build &&
  #             export LD_LIBRARY_PATH="$(pwd)/lib:$LD_LIBRARY_PATH" &&
  #             cd build &&
  #             ctest -R test_robot_state --verbose
  #           '

  # # Step 3: Run Controllers test
  # test_controllers:
  #   needs: build-docker
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/download-artifact@v4
  #       with:
  #         name: meeran_assignment
  #     - name: Load Docker image
  #       run: docker load < meeran_assignment.tar.gz
  #     - name: Run Controllers test
  #       run: |
  #         docker run --rm \
  #           -v "${{ github.workspace }}/task_assignment:/assignment" \
  #           -w /assignment \
  #           meeran_assignment \
  #           bash -c '
  #             cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug &&
  #             cmake --build build &&
  #             export LD_LIBRARY_PATH="$(pwd)/lib:$LD_LIBRARY_PATH" &&
  #             cd build &&
  #             ctest -R test_controllers --verbose
  #           '

  # # Step 4: Run Demo test
  # test_demos:
  #   needs: build-docker
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/download-artifact@v4
  #       with:
  #         name: meeran_assignment
  #     - name: Load Docker image
  #       run: docker load < meeran_assignment.tar.gz
  #     - name: Run Demos test
  #       run: |
  #         docker run --rm \
  #           -v "${{ github.workspace }}/task_assignment:/assignment" \
  #           -w /assignment \
  #           meeran_assignment \
  #           bash -c '
  #             cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug &&
  #             cmake --build build &&
  #             export LD_LIBRARY_PATH="$(pwd)/lib:$LD_LIBRARY_PATH" &&
  #             cd build &&
  #             ctest -R test_demos --verbose
  #           '
