name: C++ Build & Test (Robot State)

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build-test-robot-state:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential cmake git python3 python3-pip \
            libeigen3-dev libtinyxml-dev libconsole-bridge-dev \
            liburdfdom-dev liburdfdom-headers-dev libassimp-dev \
            libboost-all-dev
          sudo ldconfig

      - name: Configure & Build
        run: |
          cd task_assignment
          cmake -S . -B build
          cmake --build build

      - name: Debug missing libraries
        run: |
          echo "Checking dependencies for test_robot_state"
          ldd task_assignment/build/tests/test_robot_state | grep "not found" || true

      - name: Run Robot State Test
        run: |
          cd task_assignment/build
          ctest -R test_robot_state --verbose
