name: C++ Build & Test

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake python3 python3-pip libeigen3-dev libtinyxml-dev
          sudo ldconfig

      - name: Configure & Build
        run: |
          cd task_assignment
          cmake -S . -B build
          cmake --build build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: task_assignment/build

  test_robot_state:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install runtime dependencies
        run: |
          sudo apt update
          sudo apt install -y libtinyxml-dev libeigen3-dev
          sudo ldconfig

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: task_assignment/build

      - name: Fix test permissions
        run: |
          chmod +x task_assignment/build/tests/*

      - name: Run Robot State Tests
        run: |
          export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH
          cd task_assignment/build
          ctest -R "^test_robot_state$" --verbose
