name: C++ Build & Test (Robot State Only)

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake python3 python3-pip libeigen3-dev

      - name: Configure, Build, and Test (Robot State Only)
        run: |
          cd task_assignment
          cmake -S . -B build
          cmake --build build
          export LD_LIBRARY_PATH="$(pwd)/lib:$LD_LIBRARY_PATH"
          cd build
          ctest -R robot_test --verbose
