name: C++ Build & Test

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y software-properties-common\
            build-essential \
            cmake \
            git \
            python3 \
            python3-pip \
            libgl1 \
            libsm6 \ 
            libxext6 \
            libeigen3-dev \
            libtinyxml-dev
          sudo ldconfig

      - name: Configure & Build
        run: |
          cd task_assignment
          cmake -S . -B build
          cmake --build build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: task_assignment/build

  test_robot_state:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: task_assignment/build

      - name: Fix test permissions
        run: |
          chmod +x task_assignment/build/tests/*

      - name: Run Robot State Tests
        run: |
          export LD_LIBRARY_PATH=$(pwd)/lib:$LD_LIBRARY_PATH
          cd task_assignment/build
          ctest -R test_robot_state --verbose

  test_controllers:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: task_assignment/build

      - name: Fix test permissions
        run: |
          chmod +x task_assignment/build/tests/*

      - name: Run Controller Tests
        run: |
          export LD_LIBRARY_PATH=$(pwd)/lib:$LD_LIBRARY_PATH
          cd task_assignment/build
          ctest -R test_controllers --verbose

  test_demos:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: task_assignment/build

      - name: Fix test permissions
        run: |
          chmod +x task_assignment/build/tests/*

      - name: Run Demo Tests
        run: |
          export LD_LIBRARY_PATH=$(pwd)/lib:$LD_LIBRARY_PATH
          cd task_assignment/build
          ctest -R test_demos --verbose
