name: C++ Build & Test

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential cmake python3 python3-pip libeigen3-dev

    - name: Configure, Build, and Test
      run: |
        cd task_assignment_robot_control_v1.0.6/task_assignment
        cmake -S . -B build
        cmake --build build
        cd build
        ctest --verbose
