name: Test Demos

on:
  workflow_dispatch:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  test_demos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t meeran_assignment ./task_assignment

      - name: Run Demos test
        run: |
          docker run --rm \
            -v "${{ github.workspace }}/task_assignment:/assignment" \
            -w /assignment \
            meeran_assignment \
            bash -c '
              cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug &&
              cmake --build build &&
              export LD_LIBRARY_PATH="$(pwd)/lib:$LD_LIBRARY_PATH" &&
              cd build &&
              ctest -R test_demos --verbose
            '
